name: Build Docker Images

on:
  push:
    branches:
      - develop
      - release/*
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build and Push Dev Image
        if: github.ref == 'refs/heads/develop'
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          docker buildx build --platform linux/amd64,linux/arm64 -t utsavnetops/flask-k8s-ops:$VERSION-dev -t utsavnetops/flask-k8s-ops:${{ github.sha }}-dev -f Dockerfile --push .

      - name: Build and Push Staging Image
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/heads\/release\///')
          docker buildx build --platform linux/amd64,linux/arm64 -t utsavnetops/flask-k8s-ops:$VERSION-staging -t utsavnetops/flask-k8s-ops:${{ github.sha }}-staging -f Dockerfile --push .

      - name: Build and Push Prod Image
        if: startsWith(github.ref, 'refs/heads/v')
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          docker buildx build --platform linux/amd64,linux/arm64 -t utsavnetops/flask-k8s-ops:$VERSION -t utsavnetops/flask-k8s-ops:${{ github.sha }} -f Dockerfile --push .
