name: Build Docker Images

on:
  push:
    branches:
      - develop/*
      - release/*
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=$(echo ${branch_name:8})" >> $GITHUB_ENV

      - name: Build and Push Dev Image
        if: startsWith(github.ref, 'refs/heads/develop/')
        run: |
          VERSION=$(echo $branch | tr '/' '-')
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t utsavnetops/flask-k8s-ops:$VERSION-dev-${{ github.sha }} \
            -t utsavnetops/flask-k8s-ops:latest-dev \
            -f Dockerfile --push .

      - name: Build and Push Staging Image
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          VERSION=$(echo $branch | tr '/' '-')
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t utsavnetops/flask-k8s-ops:$VERSION-staging-${{ github.sha }} \
            -t utsavnetops/flask-k8s-ops:latest-staging \
            -f Dockerfile --push .

      - name: Build and Push Prod Image
        if: startsWith(github.ref, 'refs/heads/v')
        run: |
          VERSION=$(echo $branch | tr '/' '-')
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t utsavnetops/flask-k8s-ops:$VERSION-${{ github.sha }} \
            -t utsavnetops/flask-k8s-ops:latest \
            -f Dockerfile --push .
